---
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npm run format
      - uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.event_name == 'push' && github.ref_name == 'main'
        with:
          branch: release
          folder: .
